name: "tag-auto-release"
on:
  push:
    tags:
      - "v*"

jobs:
  build_windows:
    name: Build On Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: target/release/

  build_x86_64-linux-musl:
    name: Build On x86_64-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - name: Upload x86_64-linux-musl Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-linux-musl-build
          path: target/x86_64-unknown-linux-musl/release/

  build_aarch64-linux-musl:
    name: Build On aarch64-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-musl
      - name: Upload aarch64-linux-musl Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-linux-musl-build
          path: target/aarch64-unknown-linux-musl/release/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_windows, build_x86_64-linux-musl, build_aarch64-linux-musl]
    steps:
      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-build
          path: ./windows-build

      - name: Download x86_64-linux-musl Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: x86_64-linux-musl-build
          path: ./x86_64-linux-musl-build

      - name: Download aarch64-linux-musl Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: aarch64-linux-musl-build
          path: ./aarch64-linux-musl-build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Windows Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-build
          asset_name: windows-build.zip
          asset_content_type: application/zip

      - name: Upload x86_64-linux-musl Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./x86_64-linux-musl-build
          asset_name: x86_64-linux-musl-build.zip
          asset_content_type: application/zip

      - name: Upload aarch64-linux-musl Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./aarch64-linux-musl-build
          asset_name: aarch64-linux-musl-build.zip
          asset_content_type: application/zip
